server:
  port: 8080
  read_timeout: 30
  write_timeout: 30

spotify:
  client_id: "${SPOTIFY_CLIENT_ID}"
  client_secret: "${SPOTIFY_CLIENT_SECRET}"
  redirect_uri: " https://c1ed8737edac.ngrok-free.app/callback"

logging:
  level: "info"
  format: "json"
