server:
  port: 8080
  read_timeout: 30
  write_timeout: 30

spotify:
  client_id: "${SPOTIFY_CLIENT_ID}"
  client_secret: "${SPOTIFY_CLIENT_SECRET}"
  redirect_uri: "http://localhost:8080/callback"

logging:
  level: "info"
  format: "json"
